---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/

# pserver07:/data/compose/6/config/settings.yaml#

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey

title: PACNET Dashboard
description: A description of my awesome homepage

#useEqualHeights: true

fiveColumns: true
# bookmarksStyle: icons

#https://gethomepage.dev/configs/settings/#background-image
background:
    image: https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80
    blur: xl # sm, "", md, xl... see https://tailwindcss.com/docs/backdrop-blur
    saturate: 50 # 0, 50, 100... see https://tailwindcss.com/docs/backdrop-saturate
    brightness: 100 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness
    opacity: 50 # 0-100

#cardBlur: sm # sm, "", md, etc... see https://tailwindcss.com/docs/backdrop-blur

#in docker : volumes: mount - "/my/homepage/images:/app/public/images"
#then in settings: background: /images/background.png


layout:
    Core:
        header: true
        # style: column
        # rows: 4
    Access:
        header: true
    # style: row
    # columns: 3
        Access Points:
            header: false
            style: row
            columns: 2
        CPL:
            header: false
            style: row
            columns: 2
    Servers:
        header: true
    NAS:
        header: true
    Virtual machines:
        header: true
    Monitoring:
    IoT and Smarthome:
        icon: home-assistant.png
    Portainer:
    Network management:
    Calendar:
    
    
# layout:
    # Core: #name of service or Bookmark
        # tab: Core infrastructure #Display name of tab
        # style: row
        # columns: 5
    # Access:
        # tab: Access infrastructure
        # style: row
        # columns: 5
    # Servers:
        # tab: Servers
        # style: row
        # columns: 5
        # icon: https://cdn-icons-png.flaticon.com/512/252/252035.png
    # NAS:
    # Virtual machines:
    # Monitoring:
    # IoT and Smarthome:
        # icon: home-assistant.png
    # Portainer:
    # Network management:
    # Online services:
    # Calendar:
    
    

# examples
# layout:
  # ...
  # Bookmark Group on First Tab:
    # tab: First

  # First Service Group:
    # tab: First
    # style: row
    # columns: 4

  # Second Service Group:
    # tab: Second
    # columns: 4

  # Third Service Group:
    # tab: Third
    # style: row

  # Bookmark Group on Fourth Tab:
    # tab: Fourth

  # Service Group on every Tab:
    # style: row
    # columns: 4
