---
- name: Create deployment directory
  file:
    path: "{{ beszel_deploy_path }}"
    state: directory
    mode: '0755'

- name: Copy Compose files to host
  copy:
    src: "{{ item }}"
    dest: "{{ beszel_deploy_path }}/{{ item }}"
    mode: '0644'
  loop: "{{ compose_files }}"

- name: Launch services via docker-compose
  community.docker.docker_compose_v2:
    project_src: "{{ beszel_deploy_path }}"
    files: "{{ compose_files }}"
    state: present
