[local]
localhost ansible_connection=local

[raspberry_pis]
localhost ansible_connection=local
pi4-01 ansible_host=pi4-01.dmz

[ubuntu_servers]
pserver04 ansible_host=pserver04.dmz
pserver2502 ansible_host=pserver2502.dmz

[all_servers:children]
ubuntu_servers
raspberry_pis

[linux_servers:children]
ubuntu_servers
raspberry_pis
