# Local
[local]
pi5-01 ansible_connection=local

# Raspberry Pis
[raspberry_pis]
pi5-01 ansible_host=pi5-01.dmz
pi4-01 ansible_host=pi4-01.dmz

# Physical Ubuntu servers
[ubuntu_servers]
pserver04  ansible_host=pserver04.dmz

# VMware virtual machines
[vservers]
vserver04  ansible_host=vserver04.dmz

# Debian servers
[debian_servers]
pserver2502 ansible_host=pserver2502.dmz

# Role-based groups
[docker_hosts:children]
raspberry_pis
ubuntu_servers
vservers
debian_servers

[traefik_hosts:children]
raspberry_pis
ubuntu_servers
vservers
debian_servers

[portainer_agents:children]
raspberry_pis
ubuntu_servers
vservers
debian_servers

# OS rollup
[linux_servers:children]
ubuntu_servers
vservers
debian_servers
raspberry_pis

# All managed nodes
[all_servers:children]
linux_servers
