---
- name: Create app directory
  file:
    path: "{{ app_dir }}"
    state: directory
    owner: "{{ admin_user }}"
    group: "{{ admin_user }}"
    mode: "0755"

- name: Copy docker-compose.yml
  copy:
    src: "docker-compose.yml"
    dest: "{{ app_dir }}/docker-compose.yml"
    owner: "{{ admin_user }}"
    group: "{{ admin_user }}"
    mode: "0644"

- name: Deploy with docker compose
  community.docker.docker_compose_v2:
    project_src: "{{ app_dir }}"
    state: present
  ignore_errors: "{{ ansible_check_mode }}"

