services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    hostname: "homepage"
    ports:
      - 3010:3000
    volumes:
      - ./config:/app/config # Make sure your local config directory exists
      #- /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations, see alternative methods
      - ./images:/app/public/images
      - ./icons:/app/public/icons
    environment:
      PUID: 1000
      PGID: 1000
      HOMEPAGE_ALLOWED_HOSTS: <homepage.server.com>
    restart: unless-stopped
    networks:
      - dns #adapt to match traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homepage.rule=Host(`<homepage.server.lan>`)" # >> change ulr
      - "traefik.http.routers.homepage.entrypoints=web"


networks:
  dns: # adapt if needed
    external: true
