---
- name: Deploy Beszel & Beszel-Agent
  hosts: "{{ target_group | default('linux_servers') }}"
  become: yes

  vars_files:
    - vars/container.yml

  tasks:
    - import_tasks: tasks/container.yml
