# this version uses a variable instead of hardcoding the host
# ansible-playbook deploy_container.yml -e "target_group=pserver04"
# or ansible-playbook deploy_container.yml --limit pserver04

---
- name: Deploy Beszel & Beszel-Agent
  hosts: "{{ target_group | default('linux_servers') }}"
  become: yes

  vars_files:
    - vars/stack.yml

  tasks:
    - import_tasks: tasks/stack.yml
