services:
  portainer:
    image: portainer/portainer-ce:lts
    container_name: portainer
    restart: unless-stopped
    ports:
      - "8000:8000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer-secure.rule=Host(`portainer.lan`)"
      - "traefik.http.routers.portainer-secure.entrypoints=websecure"
      - "traefik.http.routers.portainer-secure.tls=true"
      - "traefik.http.routers.portainer-secure.service=portainer-svc"
      - "traefik.http.routers.portainer-plain.rule=Host(`portainer.pacnet.be`)"
      - "traefik.http.routers.portainer-plain.entrypoints=web"
      - "traefik.http.routers.portainer-plain.service=portainer-svc"
      - "traefik.http.services.portainer-svc.loadbalancer.server.port=9443"
      - "traefik.http.services.portainer-svc.loadbalancer.server.scheme=https"

    networks:
      - proxy

volumes:
  portainer_data:
    external: true

networks:
  proxy:
    external: true

